export const featuredProducts = [
  {
    id: "1",
    name: "Giày chạy bộ Nike Air Zoom",
    price: 2500000,
    originalPrice: 3000000,
    image: "/placeholder.svg?height=240&width=240",
    category: "Giày",
    isNew: false,
    isSale: true,
  },
  {
    id: "2",
    name: "Áo thun thể thao Adidas",
    price: 450000,
    image: "/placeholder.svg?height=240&width=240",
    category: "Quần áo",
    isNew: true,
    isSale: false,
  },
  {
    id: "3",
    name: "Quần short tập gym Under Armour",
    price: 650000,
    image: "/placeholder.svg?height=240&width=240",
    category: "Quần áo",
    isNew: false,
    isSale: false,
  },
  {
    id: "4",
    name: "Bóng đá Nike Strike",
    price: 750000,
    originalPrice: 900000,
    image: "/placeholder.svg?height=240&width=240",
    category: "Dụng cụ",
    isNew: false,
    isSale: true,
  },
  {
    id: "5",
    name: "Túi thể thao Puma",
    price: 850000,
    image: "/placeholder.svg?height=240&width=240",
    category: "Phụ kiện",
    isNew: true,
    isSale: false,
  },
  {
    id: "6",
    name: "Vợt tennis Wilson",
    price: 1950000,
    image: "/placeholder.svg?height=240&width=240",
    category: "Dụng cụ",
    isNew: false,
    isSale: false,
  },
  {
    id: "7",
    name: "Găng tay tập gym",
    price: 350000,
    image: "/placeholder.svg?height=240&width=240",
    category: "Phụ kiện",
    isNew: false,
    isSale: false,
  },
  {
    id: "8",
    name: "Thảm tập yoga",
    price: 450000,
    originalPrice: 550000,
    image: "/placeholder.svg?height=240&width=240",
    category: "Dụng cụ",
    isNew: false,
    isSale: true,
  },
]

export const categories = [
  {
    id: "giay",
    name: "Giày thể thao",
    image: "/placeholder.svg?height=160&width=320",
    productCount: 45,
  },
  {
    id: "quan-ao",
    name: "Quần áo",
    image: "/placeholder.svg?height=160&width=320",
    productCount: 78,
  },
  {
    id: "dung-cu",
    name: "Dụng cụ thể thao",
    image: "/placeholder.svg?height=160&width=320",
    productCount: 36,
  },
  {
    id: "phu-kien",
    name: "Phụ kiện",
    image: "/placeholder.svg?height=160&width=320",
    productCount: 29,
  },
  {
    id: "dinh-duong",
    name: "Dinh dưỡng thể thao",
    image: "/placeholder.svg?height=160&width=320",
    productCount: 15,
  },
  {
    id: "may-chay-bo",
    name: "Máy chạy bộ & Thiết bị tập",
    image: "/placeholder.svg?height=160&width=320",
    productCount: 22,
  },
]
